apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: jhipster-poc
spec:
  ingressClassName: nginx
  rules:
    - host: gateway.jhipster-poc.spindox.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  name: http
