apiVersion: v1
kind: Secret
metadata:
  name: products-postgresql
  namespace: jhipster-poc
  labels:
    app: products-postgresql
type: Opaque
data:
  postgresql-password: YTgyNDI1NWJhMzQ2YTIwMjBmY2ZhMTk5ZjY2MzIwN2YwMzhlMWJkY2UwZTc5YTE3ODY3MGVjMzI3MDgy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-postgresql
  namespace: jhipster-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-postgresql
  template:
    metadata:
      labels:
        app: products-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:16.1
          env:
            - name: POSTGRES_USER
              value: products
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: products-postgresql
  namespace: jhipster-poc
spec:
  selector:
    app: products-postgresql
  ports:
    - port: 5432
