#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MGQ1MjI2ZTc1YmNmNWM4NTg4YjU4MTYyY2ZmOTM4YmQwMGNkMWRjYzFjZWM1YTg5ZDJlOTI1M2EwODYwZTk4ODk5N2RkN2NlMTQyYjJkM2E0ZTAyMGQyZmI4MGE4Y2NhMDBkOQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
