apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: jhipster-poc
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name:  JHipster Registry
      status: Connected to the JHipster Registry running in Kubernetes
    eureka:
      client:
        initial-instance-info-replication-interval-seconds: 15
        instance-info-replication-interval-seconds: 15
        registry-fetch-interval-seconds: 15
        fetch-registry: true
        register-with-eureka: true
        eureka-service-url-poll-interval-seconds: 15
      instance:
        lease-renewal-interval-in-seconds: 10
        registry-default-open-for-traffic-count: 0
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: OTBhNGM1ZWM1NmQyNjdiOTg2NTlkOWRmNGIyYTkyYjlhNGIwZTA4ZmJhYzE2MWYyMjY1Njk5MGFhMGM4ZWRmZDdmYzdmNWQ4MDBkNTRjMDkwYmM4MjkxMGZkMmRiMWQ0MDA0Nw==
  # app specific configuration
  jhipster-registry.yml: |-
    eureka:
      client:
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.jhipster-poc.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@jhipster-registry-1.jhipster-registry.jhipster-poc.svc.cluster.local:8761/eureka/
