apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: stefanofiorespindox/gateway
      context: ../gateway
      jib: {}
    - image: stefanofiorespindox/products
      context: ../products
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
